### ISSUE TITLE
Disallow return outside of function

### ISSUE THREAD

**Issue by yshin4** [jtorre39/jen#2]
Statement          = Conditional | Loop | Declaration | Assignment | FuncDec
                             | TypeDec | ReturnExp

Statement currently contains ReturnExp but this should be removed.
However, this causes a problem for fibonacci.jen because it contains return in the if statement and our ohm grammar does not account for any other return statements other than the one at the end of the function. So in the future we should be implementing conditionals and loops that can return, so that it can be called by the FuncDec rule. However, because hw1 is due tomorrow we will allow return outside of function for now.

Future syntax (bad program) error to implement 
return.jen
```
return 1
```
should error since we don't want to return outside of the function.

**Comment by rtoal** [comment]
It's easiest to just write the grammar so that a statement can be a return statement any time. A return statement outside of a function will be a semantic error, not a syntax error. That's how I usually do it (see for example https://github.com/rtoal/plainscript/blob/master/ast/return-statement.js).

**Comment by yshin4** [comment]
Python and JavaScript had it as a syntax error so I thought it would be appropriate, but we will try your way once we get to implement syntax. Thanks, @rtoal!

**Comment by jtorre39** [comment]
Closing this issue, as we this will be addressed anyway during semantic analysis.
